-- Life Quest math seed chunk 3/4
-- 5 fields / 68 topics

begin;

insert into public.quest_fields (field_id, subject_id, name, sort_order, active) values
  ('math-counting-probability', 'math', '場合の数・確率', 110, true),
  ('math-data-statistics', 'math', 'データ・統計', 120, true),
  ('math-sequences', 'math', '数列', 130, true),
  ('math-vectors', 'math', 'ベクトル', 140, true),
  ('math-complex-plane-curves', 'math', '複素数平面・曲線', 150, true)
on conflict (field_id) do update set
  subject_id = excluded.subject_id,
  name = excluded.name,
  sort_order = excluded.sort_order,
  active = excluded.active;

insert into public.quest_topics (topic_id, field_id, name, source, importance, recommended_order, active) values
  ('math-counting-probability-001', 'math-counting-probability', '起こり得る場合の整理', '小学算数・中学数学', 2, 10, true),
  ('math-counting-probability-002', 'math-counting-probability', '樹形図による場合分け', '小学算数・中学数学', 2, 20, true),
  ('math-counting-probability-003', 'math-counting-probability', '確率の意味', '小学算数・中学数学', 2, 30, true),
  ('math-counting-probability-004', 'math-counting-probability', '相対度数と確率', '小学算数・中学数学', 2, 40, true),
  ('math-counting-probability-005', 'math-counting-probability', '数え上げの原則', '高校 数学A', 2, 50, true),
  ('math-counting-probability-006', 'math-counting-probability', '順列', '高校 数学A', 2, 60, true),
  ('math-counting-probability-007', 'math-counting-probability', '組合せ', '高校 数学A', 2, 70, true),
  ('math-counting-probability-008', 'math-counting-probability', '確率の基本法則', '高校 数学A', 2, 80, true),
  ('math-counting-probability-009', 'math-counting-probability', '余事象・排反事象', '高校 数学A', 2, 90, true),
  ('math-counting-probability-010', 'math-counting-probability', '独立な試行と反復試行', '高校 数学A', 2, 100, true),
  ('math-counting-probability-011', 'math-counting-probability', '条件付き確率', '高校 数学A', 2, 110, true),
  ('math-counting-probability-012', 'math-counting-probability', '期待値', '高校 数学A', 2, 120, true),
  ('math-data-statistics-001', 'math-data-statistics', 'データの分類と表', '小学算数', 2, 10, true),
  ('math-data-statistics-002', 'math-data-statistics', '絵・棒グラフ', '小学算数', 2, 20, true),
  ('math-data-statistics-003', 'math-data-statistics', '折れ線グラフ', '小学算数', 2, 30, true),
  ('math-data-statistics-004', 'math-data-statistics', '円グラフ・帯グラフ', '小学算数', 2, 40, true),
  ('math-data-statistics-005', 'math-data-statistics', '平均', '小学算数', 2, 50, true),
  ('math-data-statistics-006', 'math-data-statistics', '代表値の考え方', '小学算数', 2, 60, true),
  ('math-data-statistics-007', 'math-data-statistics', '度数分布表', '中学数学', 2, 70, true),
  ('math-data-statistics-008', 'math-data-statistics', 'ヒストグラム', '中学数学', 2, 80, true),
  ('math-data-statistics-009', 'math-data-statistics', '相対度数', '中学数学', 2, 90, true),
  ('math-data-statistics-010', 'math-data-statistics', '中央値・最頻値・範囲', '中学数学', 2, 100, true),
  ('math-data-statistics-011', 'math-data-statistics', '四分位数・四分位範囲', '中学数学', 2, 110, true),
  ('math-data-statistics-012', 'math-data-statistics', '箱ひげ図', '中学数学', 2, 120, true),
  ('math-data-statistics-013', 'math-data-statistics', '標本調査', '中学数学', 2, 130, true),
  ('math-data-statistics-014', 'math-data-statistics', '分散', '高校 数学I', 2, 140, true),
  ('math-data-statistics-015', 'math-data-statistics', '標準偏差', '高校 数学I', 2, 150, true),
  ('math-data-statistics-016', 'math-data-statistics', '散布図', '高校 数学I', 2, 160, true),
  ('math-data-statistics-017', 'math-data-statistics', '相関係数', '高校 数学I', 2, 170, true),
  ('math-data-statistics-018', 'math-data-statistics', '外れ値', '高校 数学I', 2, 180, true),
  ('math-data-statistics-019', 'math-data-statistics', '仮説検定の考え方', '高校 数学I', 2, 190, true),
  ('math-data-statistics-020', 'math-data-statistics', '確率変数と確率分布', '高校 数学B', 2, 200, true),
  ('math-data-statistics-021', 'math-data-statistics', '確率変数の平均・分散・標準偏差', '高校 数学B', 2, 210, true),
  ('math-data-statistics-022', 'math-data-statistics', '二項分布', '高校 数学B', 2, 220, true),
  ('math-data-statistics-023', 'math-data-statistics', '連続型確率変数', '高校 数学B', 2, 230, true),
  ('math-data-statistics-024', 'math-data-statistics', '正規分布', '高校 数学B', 2, 240, true),
  ('math-data-statistics-025', 'math-data-statistics', '母集団と標本', '高校 数学B', 2, 250, true),
  ('math-data-statistics-026', 'math-data-statistics', '無作為抽出', '高校 数学B', 2, 260, true),
  ('math-data-statistics-027', 'math-data-statistics', '標本分布', '高校 数学B', 2, 270, true),
  ('math-data-statistics-028', 'math-data-statistics', '母平均の推定', '高校 数学B', 2, 280, true),
  ('math-data-statistics-029', 'math-data-statistics', '区間推定', '高校 数学B', 2, 290, true),
  ('math-data-statistics-030', 'math-data-statistics', '仮説検定', '高校 数学B', 2, 300, true),
  ('math-sequences-001', 'math-sequences', '数列と一般項', '高校 数学B', 2, 10, true),
  ('math-sequences-002', 'math-sequences', '等差数列', '高校 数学B', 2, 20, true),
  ('math-sequences-003', 'math-sequences', '等比数列', '高校 数学B', 2, 30, true),
  ('math-sequences-004', 'math-sequences', 'Σと数列の和', '高校 数学B', 2, 40, true),
  ('math-sequences-005', 'math-sequences', 'いろいろな数列の和', '高校 数学B', 2, 50, true),
  ('math-sequences-006', 'math-sequences', '漸化式', '高校 数学B', 2, 60, true),
  ('math-sequences-007', 'math-sequences', '数学的帰納法', '高校 数学B', 2, 70, true),
  ('math-vectors-001', 'math-vectors', 'ベクトルとは何か', '高校 数学C', 2, 10, true),
  ('math-vectors-002', 'math-vectors', 'ベクトルの加法・減法・実数倍', '高校 数学C', 2, 20, true),
  ('math-vectors-003', 'math-vectors', 'ベクトルの成分表示', '高校 数学C', 2, 30, true),
  ('math-vectors-004', 'math-vectors', 'ベクトルの内積', '高校 数学C', 2, 40, true),
  ('math-vectors-005', 'math-vectors', '位置ベクトル', '高校 数学C', 2, 50, true),
  ('math-vectors-006', 'math-vectors', 'ベクトルによる平面図形の表現', '高校 数学C', 2, 60, true),
  ('math-vectors-007', 'math-vectors', '空間座標', '高校 数学C', 2, 70, true),
  ('math-vectors-008', 'math-vectors', '空間ベクトル', '高校 数学C', 2, 80, true),
  ('math-vectors-009', 'math-vectors', 'ベクトルによる空間図形の表現', '高校 数学C', 2, 90, true),
  ('math-complex-plane-curves-001', 'math-complex-plane-curves', '複素数平面', '高校 数学C', 2, 10, true),
  ('math-complex-plane-curves-002', 'math-complex-plane-curves', '複素数の極形式', '高校 数学C', 2, 20, true),
  ('math-complex-plane-curves-003', 'math-complex-plane-curves', '複素数の乗除と図形的意味', '高校 数学C', 2, 30, true),
  ('math-complex-plane-curves-004', 'math-complex-plane-curves', 'ド・モアブルの定理', '高校 数学C', 2, 40, true),
  ('math-complex-plane-curves-005', 'math-complex-plane-curves', '放物線', '高校 数学C', 2, 50, true),
  ('math-complex-plane-curves-006', 'math-complex-plane-curves', '楕円', '高校 数学C', 2, 60, true),
  ('math-complex-plane-curves-007', 'math-complex-plane-curves', '双曲線', '高校 数学C', 2, 70, true),
  ('math-complex-plane-curves-008', 'math-complex-plane-curves', '媒介変数表示', '高校 数学C', 2, 80, true),
  ('math-complex-plane-curves-009', 'math-complex-plane-curves', '極座標', '高校 数学C', 2, 90, true),
  ('math-complex-plane-curves-010', 'math-complex-plane-curves', '極方程式', '高校 数学C', 2, 100, true)
on conflict (topic_id) do update set
  field_id = excluded.field_id,
  name = excluded.name,
  source = excluded.source,
  importance = excluded.importance,
  recommended_order = excluded.recommended_order,
  active = excluded.active;

commit;
