-- Life Quest math seed chunk 1/4
-- 5 fields / 76 topics

begin;

insert into public.quest_fields (field_id, subject_id, name, sort_order, active) values
  ('math-number-calculation', 'math', '数と計算', 10, true),
  ('math-integer-properties', 'math', '整数の性質', 20, true),
  ('math-quantity-ratio-percent', 'math', '量・比・割合', 30, true),
  ('math-algebraic-expressions', 'math', '文字と式', 40, true),
  ('math-equations-inequalities', 'math', '方程式・不等式', 50, true)
on conflict (field_id) do update set
  subject_id = excluded.subject_id,
  name = excluded.name,
  sort_order = excluded.sort_order,
  active = excluded.active;

insert into public.quest_topics (topic_id, field_id, name, source, importance, recommended_order, active) values
  ('math-number-calculation-001', 'math-number-calculation', '数の数え方・順序・大小', '小学算数', 2, 10, true),
  ('math-number-calculation-002', 'math-number-calculation', '十進位取り記数法', '小学算数', 2, 20, true),
  ('math-number-calculation-003', 'math-number-calculation', '加法と減法', '小学算数', 2, 30, true),
  ('math-number-calculation-004', 'math-number-calculation', '加法・減法の筆算', '小学算数', 2, 40, true),
  ('math-number-calculation-005', 'math-number-calculation', '乗法の意味と九九', '小学算数', 2, 50, true),
  ('math-number-calculation-006', 'math-number-calculation', '乗法の筆算', '小学算数', 2, 60, true),
  ('math-number-calculation-007', 'math-number-calculation', '除法の意味と余り', '小学算数', 2, 70, true),
  ('math-number-calculation-008', 'math-number-calculation', '除法の筆算', '小学算数', 2, 80, true),
  ('math-number-calculation-009', 'math-number-calculation', '四則演算', '小学算数', 2, 90, true),
  ('math-number-calculation-010', 'math-number-calculation', '計算のきまり（交換・結合・分配）', '小学算数', 2, 100, true),
  ('math-number-calculation-011', 'math-number-calculation', '計算の順序と括弧', '小学算数', 2, 110, true),
  ('math-number-calculation-012', 'math-number-calculation', '小数の意味と表し方', '小学算数', 2, 120, true),
  ('math-number-calculation-013', 'math-number-calculation', '小数の加法・減法', '小学算数', 2, 130, true),
  ('math-number-calculation-014', 'math-number-calculation', '小数の乗法・除法', '小学算数', 2, 140, true),
  ('math-number-calculation-015', 'math-number-calculation', '分数の意味と大きさ', '小学算数', 2, 150, true),
  ('math-number-calculation-016', 'math-number-calculation', '分数の同値・約分・通分', '小学算数', 2, 160, true),
  ('math-number-calculation-017', 'math-number-calculation', '分数の加法・減法', '小学算数', 2, 170, true),
  ('math-number-calculation-018', 'math-number-calculation', '分数の乗法・除法', '小学算数', 2, 180, true),
  ('math-number-calculation-019', 'math-number-calculation', '概数・四捨五入・見積り', '小学算数', 2, 190, true),
  ('math-number-calculation-020', 'math-number-calculation', '正の数・負の数', '中学数学', 2, 200, true),
  ('math-number-calculation-021', 'math-number-calculation', '正負の数の四則計算', '中学数学', 2, 210, true),
  ('math-number-calculation-022', 'math-number-calculation', '平方根', '中学数学', 2, 220, true),
  ('math-number-calculation-023', 'math-number-calculation', '根号を含む式の計算', '中学数学', 2, 230, true),
  ('math-number-calculation-024', 'math-number-calculation', '無理数と実数', '高校 数学I', 2, 240, true),
  ('math-number-calculation-025', 'math-number-calculation', '無理数の四則計算', '高校 数学I', 2, 250, true),
  ('math-number-calculation-026', 'math-number-calculation', '有限小数と循環小数', '高校 数学I', 2, 260, true),
  ('math-integer-properties-001', 'math-integer-properties', '偶数と奇数', '小学算数', 2, 10, true),
  ('math-integer-properties-002', 'math-integer-properties', '倍数と約数', '小学算数', 2, 20, true),
  ('math-integer-properties-003', 'math-integer-properties', '最大公約数と最小公倍数', '小学算数', 2, 30, true),
  ('math-integer-properties-004', 'math-integer-properties', '素数と素因数分解', '中学数学', 2, 40, true),
  ('math-integer-properties-005', 'math-integer-properties', '整数の除法と余り', '高校 数学A', 2, 50, true),
  ('math-integer-properties-006', 'math-integer-properties', 'ユークリッドの互除法', '高校 数学A', 2, 60, true),
  ('math-integer-properties-007', 'math-integer-properties', '記数法とn進法', '高校 数学A', 2, 70, true),
  ('math-quantity-ratio-percent-001', 'math-quantity-ratio-percent', '長さ・重さ・時間・かさの単位', '小学算数', 2, 10, true),
  ('math-quantity-ratio-percent-002', 'math-quantity-ratio-percent', '面積の意味と単位', '小学算数', 2, 20, true),
  ('math-quantity-ratio-percent-003', 'math-quantity-ratio-percent', '長方形・正方形の面積', '小学算数', 2, 30, true),
  ('math-quantity-ratio-percent-004', 'math-quantity-ratio-percent', '三角形・四角形の面積', '小学算数', 2, 40, true),
  ('math-quantity-ratio-percent-005', 'math-quantity-ratio-percent', '円の面積', '小学算数', 2, 50, true),
  ('math-quantity-ratio-percent-006', 'math-quantity-ratio-percent', '体積の意味と単位', '小学算数', 2, 60, true),
  ('math-quantity-ratio-percent-007', 'math-quantity-ratio-percent', '直方体・立方体の体積', '小学算数', 2, 70, true),
  ('math-quantity-ratio-percent-008', 'math-quantity-ratio-percent', '角柱・円柱の体積', '小学算数', 2, 80, true),
  ('math-quantity-ratio-percent-009', 'math-quantity-ratio-percent', '単位量あたりの大きさ', '小学算数', 2, 90, true),
  ('math-quantity-ratio-percent-010', 'math-quantity-ratio-percent', '速さ', '小学算数', 2, 100, true),
  ('math-quantity-ratio-percent-011', 'math-quantity-ratio-percent', '割合と百分率', '小学算数', 2, 110, true),
  ('math-quantity-ratio-percent-012', 'math-quantity-ratio-percent', '比', '小学算数', 2, 120, true),
  ('math-quantity-ratio-percent-013', 'math-quantity-ratio-percent', '比例配分と比の利用', '小学算数', 2, 130, true),
  ('math-algebraic-expressions-001', 'math-algebraic-expressions', '数量を式に表す・式を読む', '小学算数', 2, 10, true),
  ('math-algebraic-expressions-002', 'math-algebraic-expressions', '文字を用いた数量の表現', '小学算数', 2, 20, true),
  ('math-algebraic-expressions-003', 'math-algebraic-expressions', '文字式の表し方', '中学数学', 2, 30, true),
  ('math-algebraic-expressions-004', 'math-algebraic-expressions', '代入と式の値', '中学数学', 2, 40, true),
  ('math-algebraic-expressions-005', 'math-algebraic-expressions', '一次式の加法・減法', '中学数学', 2, 50, true),
  ('math-algebraic-expressions-006', 'math-algebraic-expressions', '整式の加法・減法', '中学数学', 2, 60, true),
  ('math-algebraic-expressions-007', 'math-algebraic-expressions', '単項式の乗法・除法', '中学数学', 2, 70, true),
  ('math-algebraic-expressions-008', 'math-algebraic-expressions', '文字式による数量関係の説明', '中学数学', 2, 80, true),
  ('math-algebraic-expressions-009', 'math-algebraic-expressions', '多項式の乗法', '中学数学', 2, 90, true),
  ('math-algebraic-expressions-010', 'math-algebraic-expressions', '因数分解', '中学数学', 2, 100, true),
  ('math-algebraic-expressions-011', 'math-algebraic-expressions', '二次の展開公式・因数分解公式', '高校 数学I・II', 2, 110, true),
  ('math-algebraic-expressions-012', 'math-algebraic-expressions', '三次の展開公式・因数分解公式', '高校 数学I・II', 2, 120, true),
  ('math-algebraic-expressions-013', 'math-algebraic-expressions', '多項式の除法', '高校 数学I・II', 2, 130, true),
  ('math-algebraic-expressions-014', 'math-algebraic-expressions', '分数式の四則計算', '高校 数学I・II', 2, 140, true),
  ('math-algebraic-expressions-015', 'math-algebraic-expressions', '二項定理', '高校 数学I・II', 2, 150, true),
  ('math-equations-inequalities-001', 'math-equations-inequalities', '等式と不等式', '小学算数・中学数学', 2, 10, true),
  ('math-equations-inequalities-002', 'math-equations-inequalities', '一元一次方程式', '小学算数・中学数学', 2, 20, true),
  ('math-equations-inequalities-003', 'math-equations-inequalities', '比例式', '小学算数・中学数学', 2, 30, true),
  ('math-equations-inequalities-004', 'math-equations-inequalities', '二元一次方程式', '小学算数・中学数学', 2, 40, true),
  ('math-equations-inequalities-005', 'math-equations-inequalities', '連立二元一次方程式', '小学算数・中学数学', 2, 50, true),
  ('math-equations-inequalities-006', 'math-equations-inequalities', '二次方程式', '小学算数・中学数学', 2, 60, true),
  ('math-equations-inequalities-007', 'math-equations-inequalities', '二次方程式の解の公式', '小学算数・中学数学', 2, 70, true),
  ('math-equations-inequalities-008', 'math-equations-inequalities', '一次不等式', '高校 数学I・II', 2, 80, true),
  ('math-equations-inequalities-009', 'math-equations-inequalities', '二次不等式', '高校 数学I・II', 2, 90, true),
  ('math-equations-inequalities-010', 'math-equations-inequalities', '複素数', '高校 数学I・II', 2, 100, true),
  ('math-equations-inequalities-011', 'math-equations-inequalities', '複素数の四則計算', '高校 数学I・II', 2, 110, true),
  ('math-equations-inequalities-012', 'math-equations-inequalities', '二次方程式の判別式', '高校 数学I・II', 2, 120, true),
  ('math-equations-inequalities-013', 'math-equations-inequalities', '解と係数の関係', '高校 数学I・II', 2, 130, true),
  ('math-equations-inequalities-014', 'math-equations-inequalities', '因数定理', '高校 数学I・II', 2, 140, true),
  ('math-equations-inequalities-015', 'math-equations-inequalities', '高次方程式', '高校 数学I・II', 2, 150, true)
on conflict (topic_id) do update set
  field_id = excluded.field_id,
  name = excluded.name,
  source = excluded.source,
  importance = excluded.importance,
  recommended_order = excluded.recommended_order,
  active = excluded.active;

commit;
