-- Life Quest math seed chunk 2/4
-- 5 fields / 80 topics

begin;

insert into public.quest_fields (field_id, subject_id, name, sort_order, active) values
  ('math-functions', 'math', '関数', 60, true),
  ('math-geometry', 'math', '図形', 70, true),
  ('math-trigonometry', 'math', '三角比・三角関数', 80, true),
  ('math-analytic-geometry', 'math', '図形と方程式', 90, true),
  ('math-exponential-logarithm', 'math', '指数・対数', 100, true)
on conflict (field_id) do update set
  subject_id = excluded.subject_id,
  name = excluded.name,
  sort_order = excluded.sort_order,
  active = excluded.active;

insert into public.quest_topics (topic_id, field_id, name, source, importance, recommended_order, active) values
  ('math-functions-001', 'math-functions', '伴って変わる二つの数量', '小学算数・中学数学', 2, 10, true),
  ('math-functions-002', 'math-functions', '表・式・グラフで表す関係', '小学算数・中学数学', 2, 20, true),
  ('math-functions-003', 'math-functions', '比例', '小学算数・中学数学', 2, 30, true),
  ('math-functions-004', 'math-functions', '反比例', '小学算数・中学数学', 2, 40, true),
  ('math-functions-005', 'math-functions', '座標', '小学算数・中学数学', 2, 50, true),
  ('math-functions-006', 'math-functions', '一次関数', '小学算数・中学数学', 2, 60, true),
  ('math-functions-007', 'math-functions', '一次関数の変化の割合', '小学算数・中学数学', 2, 70, true),
  ('math-functions-008', 'math-functions', '関数 y=ax²', '小学算数・中学数学', 2, 80, true),
  ('math-functions-009', 'math-functions', '関数という考え方', '高校 数学I・III', 2, 90, true),
  ('math-functions-010', 'math-functions', '二次関数とグラフ', '高校 数学I・III', 2, 100, true),
  ('math-functions-011', 'math-functions', '二次関数の最大・最小', '高校 数学I・III', 2, 110, true),
  ('math-functions-012', 'math-functions', '二次関数と方程式・不等式', '高校 数学I・III', 2, 120, true),
  ('math-functions-013', 'math-functions', '分数関数', '高校 数学I・III', 2, 130, true),
  ('math-functions-014', 'math-functions', '無理関数', '高校 数学I・III', 2, 140, true),
  ('math-functions-015', 'math-functions', '合成関数', '高校 数学I・III', 2, 150, true),
  ('math-functions-016', 'math-functions', '逆関数', '高校 数学I・III', 2, 160, true),
  ('math-geometry-001', 'math-geometry', '点・直線・線分・角', '小学算数', 2, 10, true),
  ('math-geometry-002', 'math-geometry', '平行と垂直', '小学算数', 2, 20, true),
  ('math-geometry-003', 'math-geometry', '三角形・四角形・多角形', '小学算数', 2, 30, true),
  ('math-geometry-004', 'math-geometry', '円と円周率', '小学算数', 2, 40, true),
  ('math-geometry-005', 'math-geometry', '図形の対称', '小学算数', 2, 50, true),
  ('math-geometry-006', 'math-geometry', '合同な図形', '小学算数', 2, 60, true),
  ('math-geometry-007', 'math-geometry', '拡大図・縮図', '小学算数', 2, 70, true),
  ('math-geometry-008', 'math-geometry', '立体図形の見方', '小学算数', 2, 80, true),
  ('math-geometry-009', 'math-geometry', '基本的な作図', '中学数学', 2, 90, true),
  ('math-geometry-010', 'math-geometry', '図形の移動', '中学数学', 2, 100, true),
  ('math-geometry-011', 'math-geometry', '直線と平面の位置関係', '中学数学', 2, 110, true),
  ('math-geometry-012', 'math-geometry', '見取図・展開図・投影図', '中学数学', 2, 120, true),
  ('math-geometry-013', 'math-geometry', '平行線と角', '中学数学', 2, 130, true),
  ('math-geometry-014', 'math-geometry', '多角形の内角・外角', '中学数学', 2, 140, true),
  ('math-geometry-015', 'math-geometry', '三角形の合同条件', '中学数学', 2, 150, true),
  ('math-geometry-016', 'math-geometry', '証明の考え方', '中学数学', 2, 160, true),
  ('math-geometry-017', 'math-geometry', '三角形の性質', '中学数学', 2, 170, true),
  ('math-geometry-018', 'math-geometry', '平行四辺形の性質', '中学数学', 2, 180, true),
  ('math-geometry-019', 'math-geometry', '図形の相似', '中学数学', 2, 190, true),
  ('math-geometry-020', 'math-geometry', '三角形の相似条件', '中学数学', 2, 200, true),
  ('math-geometry-021', 'math-geometry', '相似比・面積比・体積比', '中学数学', 2, 210, true),
  ('math-geometry-022', 'math-geometry', '円周角と中心角', '中学数学', 2, 220, true),
  ('math-geometry-023', 'math-geometry', '三平方の定理', '中学数学', 2, 230, true),
  ('math-geometry-024', 'math-geometry', '三角形の辺と角の関係', '高校 数学A', 2, 240, true),
  ('math-geometry-025', 'math-geometry', '三角形の内分線・外分線', '高校 数学A', 2, 250, true),
  ('math-geometry-026', 'math-geometry', '三角形の重心・内心・外心', '高校 数学A', 2, 260, true),
  ('math-geometry-027', 'math-geometry', '三角形の比と定理（チェバ・メネラウス）', '高校 数学A', 2, 270, true),
  ('math-geometry-028', 'math-geometry', '円に内接する四角形', '高校 数学A', 2, 280, true),
  ('math-geometry-029', 'math-geometry', '円の接線', '高校 数学A', 2, 290, true),
  ('math-geometry-030', 'math-geometry', '方べきの定理', '高校 数学A', 2, 300, true),
  ('math-geometry-031', 'math-geometry', '二つの円の位置関係', '高校 数学A', 2, 310, true),
  ('math-geometry-032', 'math-geometry', '空間図形の性質', '高校 数学A', 2, 320, true),
  ('math-trigonometry-001', 'math-trigonometry', '正弦・余弦・正接', '高校 数学I', 2, 10, true),
  ('math-trigonometry-002', 'math-trigonometry', '三角比の相互関係', '高校 数学I', 2, 20, true),
  ('math-trigonometry-003', 'math-trigonometry', '三角比の鈍角への拡張', '高校 数学I', 2, 30, true),
  ('math-trigonometry-004', 'math-trigonometry', '正弦定理', '高校 数学I', 2, 40, true),
  ('math-trigonometry-005', 'math-trigonometry', '余弦定理', '高校 数学I', 2, 50, true),
  ('math-trigonometry-006', 'math-trigonometry', '三角比による図形の計量', '高校 数学I', 2, 60, true),
  ('math-trigonometry-007', 'math-trigonometry', '三角形の面積と三角比', '高校 数学I', 2, 70, true),
  ('math-trigonometry-008', 'math-trigonometry', '一般角と弧度法', '高校 数学II', 2, 80, true),
  ('math-trigonometry-009', 'math-trigonometry', '三角関数', '高校 数学II', 2, 90, true),
  ('math-trigonometry-010', 'math-trigonometry', '三角関数のグラフと周期', '高校 数学II', 2, 100, true),
  ('math-trigonometry-011', 'math-trigonometry', '三角関数の基本関係', '高校 数学II', 2, 110, true),
  ('math-trigonometry-012', 'math-trigonometry', '三角関数の加法定理', '高校 数学II', 2, 120, true),
  ('math-trigonometry-013', 'math-trigonometry', '倍角・半角の公式', '高校 数学II', 2, 130, true),
  ('math-trigonometry-014', 'math-trigonometry', '三角方程式・三角不等式', '高校 数学II', 2, 140, true),
  ('math-analytic-geometry-001', 'math-analytic-geometry', '平面上の点と距離', '高校 数学II', 2, 10, true),
  ('math-analytic-geometry-002', 'math-analytic-geometry', '線分の内分点・外分点', '高校 数学II', 2, 20, true),
  ('math-analytic-geometry-003', 'math-analytic-geometry', '直線の方程式', '高校 数学II', 2, 30, true),
  ('math-analytic-geometry-004', 'math-analytic-geometry', '二直線の関係', '高校 数学II', 2, 40, true),
  ('math-analytic-geometry-005', 'math-analytic-geometry', '円の方程式', '高校 数学II', 2, 50, true),
  ('math-analytic-geometry-006', 'math-analytic-geometry', '円と直線の位置関係', '高校 数学II', 2, 60, true),
  ('math-analytic-geometry-007', 'math-analytic-geometry', '軌跡', '高校 数学II', 2, 70, true),
  ('math-analytic-geometry-008', 'math-analytic-geometry', '不等式の表す領域', '高校 数学II', 2, 80, true),
  ('math-exponential-logarithm-001', 'math-exponential-logarithm', '指数法則と指数の拡張', '高校 数学II', 2, 10, true),
  ('math-exponential-logarithm-002', 'math-exponential-logarithm', '累乗根', '高校 数学II', 2, 20, true),
  ('math-exponential-logarithm-003', 'math-exponential-logarithm', '指数関数', '高校 数学II', 2, 30, true),
  ('math-exponential-logarithm-004', 'math-exponential-logarithm', '指数関数のグラフ', '高校 数学II', 2, 40, true),
  ('math-exponential-logarithm-005', 'math-exponential-logarithm', '対数の意味', '高校 数学II', 2, 50, true),
  ('math-exponential-logarithm-006', 'math-exponential-logarithm', '対数の性質と計算', '高校 数学II', 2, 60, true),
  ('math-exponential-logarithm-007', 'math-exponential-logarithm', '対数関数', '高校 数学II', 2, 70, true),
  ('math-exponential-logarithm-008', 'math-exponential-logarithm', '対数関数のグラフ', '高校 数学II', 2, 80, true),
  ('math-exponential-logarithm-009', 'math-exponential-logarithm', '常用対数', '高校 数学II', 2, 90, true),
  ('math-exponential-logarithm-010', 'math-exponential-logarithm', '指数・対数方程式と不等式', '高校 数学II', 2, 100, true)
on conflict (topic_id) do update set
  field_id = excluded.field_id,
  name = excluded.name,
  source = excluded.source,
  importance = excluded.importance,
  recommended_order = excluded.recommended_order,
  active = excluded.active;

commit;
