-- Life Quest presets: 英語（テスト得点の区切り）・筋力（たたき台）
-- 2026-09-27 Keita依頼。migration 005 適用後に投入する。
-- 各区切りはチェック型トピック。同じ分野内は一つ下の区切りを前提にし、NEXTが次の区切りを指す。
-- 再実行可能（on conflict）。

begin;

insert into public.quest_subjects (subject_id, name_ja, name_en, icon, sort_order, active, preset_group) values
  ('english', '英語', 'English', '🔤', 300, true, null),
  ('strength', '筋力', 'Strength', '💪', 310, true, null)
on conflict (subject_id) do update set name_ja = excluded.name_ja, name_en = excluded.name_en, icon = excluded.icon, sort_order = excluded.sort_order, active = excluded.active, preset_group = excluded.preset_group;

insert into public.quest_fields (field_id, subject_id, name, sort_order, active) values
  ('english-toeic', 'english', 'TOEIC L&R', 10, true),
  ('english-eiken', 'english', '英検', 20, true),
  ('english-toefl', 'english', 'TOEFL iBT', 30, true),
  ('english-ielts', 'english', 'IELTS', 40, true),
  ('strength-bench', 'strength', 'ベンチプレス', 10, true),
  ('strength-squat', 'strength', 'スクワット', 20, true),
  ('strength-deadlift', 'strength', 'デッドリフト', 30, true),
  ('strength-pullup', 'strength', '懸垂', 40, true),
  ('strength-pushup', 'strength', '腕立て伏せ', 50, true),
  ('strength-grip', 'strength', '握力', 60, true)
on conflict (field_id) do update set subject_id = excluded.subject_id, name = excluded.name, sort_order = excluded.sort_order, active = excluded.active;

insert into public.quest_topics (topic_id, field_id, name, source, importance, recommended_order, active, input_type, unit) values
  ('english-toeic-400', 'english-toeic', '400点以上', null, 2, 10, true, 'check', null),
  ('english-toeic-450', 'english-toeic', '450点以上', null, 2, 20, true, 'check', null),
  ('english-toeic-500', 'english-toeic', '500点以上', null, 2, 30, true, 'check', null),
  ('english-toeic-550', 'english-toeic', '550点以上', null, 2, 40, true, 'check', null),
  ('english-toeic-600', 'english-toeic', '600点以上', null, 2, 50, true, 'check', null),
  ('english-toeic-650', 'english-toeic', '650点以上', null, 2, 60, true, 'check', null),
  ('english-toeic-700', 'english-toeic', '700点以上', null, 2, 70, true, 'check', null),
  ('english-toeic-750', 'english-toeic', '750点以上', null, 2, 80, true, 'check', null),
  ('english-toeic-800', 'english-toeic', '800点以上', null, 2, 90, true, 'check', null),
  ('english-toeic-850', 'english-toeic', '850点以上', null, 2, 100, true, 'check', null),
  ('english-toeic-900', 'english-toeic', '900点以上', null, 2, 110, true, 'check', null),
  ('english-toeic-950', 'english-toeic', '950点以上', null, 2, 120, true, 'check', null),
  ('english-toeic-990', 'english-toeic', '990点', null, 2, 130, true, 'check', null),
  ('english-eiken-3', 'english-eiken', '3級', null, 2, 10, true, 'check', null),
  ('english-eiken-pre2', 'english-eiken', '準2級', null, 2, 20, true, 'check', null),
  ('english-eiken-2', 'english-eiken', '2級', null, 2, 30, true, 'check', null),
  ('english-eiken-pre1', 'english-eiken', '準1級', null, 2, 40, true, 'check', null),
  ('english-eiken-1', 'english-eiken', '1級', null, 2, 50, true, 'check', null),
  ('english-toefl-60', 'english-toefl', '60点以上', null, 2, 10, true, 'check', null),
  ('english-toefl-70', 'english-toefl', '70点以上', null, 2, 20, true, 'check', null),
  ('english-toefl-80', 'english-toefl', '80点以上', null, 2, 30, true, 'check', null),
  ('english-toefl-90', 'english-toefl', '90点以上', null, 2, 40, true, 'check', null),
  ('english-toefl-100', 'english-toefl', '100点以上', null, 2, 50, true, 'check', null),
  ('english-toefl-110', 'english-toefl', '110点以上', null, 2, 60, true, 'check', null),
  ('english-ielts-50', 'english-ielts', '5.0以上', null, 2, 10, true, 'check', null),
  ('english-ielts-55', 'english-ielts', '5.5以上', null, 2, 20, true, 'check', null),
  ('english-ielts-60', 'english-ielts', '6.0以上', null, 2, 30, true, 'check', null),
  ('english-ielts-65', 'english-ielts', '6.5以上', null, 2, 40, true, 'check', null),
  ('english-ielts-70', 'english-ielts', '7.0以上', null, 2, 50, true, 'check', null),
  ('english-ielts-75', 'english-ielts', '7.5以上', null, 2, 60, true, 'check', null),
  ('english-ielts-80', 'english-ielts', '8.0以上', null, 2, 70, true, 'check', null),
  ('strength-bench-40', 'strength-bench', '40kg × 1回', null, 2, 10, true, 'check', null),
  ('strength-bench-60', 'strength-bench', '60kg × 1回', null, 2, 20, true, 'check', null),
  ('strength-bench-80', 'strength-bench', '80kg × 1回', null, 2, 30, true, 'check', null),
  ('strength-bench-100', 'strength-bench', '100kg × 1回', null, 2, 40, true, 'check', null),
  ('strength-bench-120', 'strength-bench', '120kg × 1回', null, 2, 50, true, 'check', null),
  ('strength-bench-140', 'strength-bench', '140kg × 1回', null, 2, 60, true, 'check', null),
  ('strength-squat-60', 'strength-squat', '60kg × 1回', null, 2, 10, true, 'check', null),
  ('strength-squat-80', 'strength-squat', '80kg × 1回', null, 2, 20, true, 'check', null),
  ('strength-squat-100', 'strength-squat', '100kg × 1回', null, 2, 30, true, 'check', null),
  ('strength-squat-120', 'strength-squat', '120kg × 1回', null, 2, 40, true, 'check', null),
  ('strength-squat-140', 'strength-squat', '140kg × 1回', null, 2, 50, true, 'check', null),
  ('strength-squat-160', 'strength-squat', '160kg × 1回', null, 2, 60, true, 'check', null),
  ('strength-squat-180', 'strength-squat', '180kg × 1回', null, 2, 70, true, 'check', null),
  ('strength-deadlift-80', 'strength-deadlift', '80kg × 1回', null, 2, 10, true, 'check', null),
  ('strength-deadlift-100', 'strength-deadlift', '100kg × 1回', null, 2, 20, true, 'check', null),
  ('strength-deadlift-120', 'strength-deadlift', '120kg × 1回', null, 2, 30, true, 'check', null),
  ('strength-deadlift-140', 'strength-deadlift', '140kg × 1回', null, 2, 40, true, 'check', null),
  ('strength-deadlift-160', 'strength-deadlift', '160kg × 1回', null, 2, 50, true, 'check', null),
  ('strength-deadlift-180', 'strength-deadlift', '180kg × 1回', null, 2, 60, true, 'check', null),
  ('strength-deadlift-200', 'strength-deadlift', '200kg × 1回', null, 2, 70, true, 'check', null),
  ('strength-pullup-1', 'strength-pullup', '1回連続', null, 2, 10, true, 'check', null),
  ('strength-pullup-5', 'strength-pullup', '5回連続', null, 2, 20, true, 'check', null),
  ('strength-pullup-10', 'strength-pullup', '10回連続', null, 2, 30, true, 'check', null),
  ('strength-pullup-15', 'strength-pullup', '15回連続', null, 2, 40, true, 'check', null),
  ('strength-pullup-20', 'strength-pullup', '20回連続', null, 2, 50, true, 'check', null),
  ('strength-pushup-10', 'strength-pushup', '10回連続', null, 2, 10, true, 'check', null),
  ('strength-pushup-30', 'strength-pushup', '30回連続', null, 2, 20, true, 'check', null),
  ('strength-pushup-50', 'strength-pushup', '50回連続', null, 2, 30, true, 'check', null),
  ('strength-pushup-100', 'strength-pushup', '100回連続', null, 2, 40, true, 'check', null),
  ('strength-grip-40', 'strength-grip', '40kg', null, 2, 10, true, 'check', null),
  ('strength-grip-50', 'strength-grip', '50kg', null, 2, 20, true, 'check', null),
  ('strength-grip-60', 'strength-grip', '60kg', null, 2, 30, true, 'check', null),
  ('strength-grip-70', 'strength-grip', '70kg', null, 2, 40, true, 'check', null)
on conflict (topic_id) do update set field_id = excluded.field_id, name = excluded.name, source = excluded.source, importance = excluded.importance, recommended_order = excluded.recommended_order, active = excluded.active, input_type = excluded.input_type, unit = excluded.unit;

insert into public.quest_topic_prerequisites (topic_id, prerequisite_topic_id) values
  ('english-toeic-450', 'english-toeic-400'),
  ('english-toeic-500', 'english-toeic-450'),
  ('english-toeic-550', 'english-toeic-500'),
  ('english-toeic-600', 'english-toeic-550'),
  ('english-toeic-650', 'english-toeic-600'),
  ('english-toeic-700', 'english-toeic-650'),
  ('english-toeic-750', 'english-toeic-700'),
  ('english-toeic-800', 'english-toeic-750'),
  ('english-toeic-850', 'english-toeic-800'),
  ('english-toeic-900', 'english-toeic-850'),
  ('english-toeic-950', 'english-toeic-900'),
  ('english-toeic-990', 'english-toeic-950'),
  ('english-eiken-pre2', 'english-eiken-3'),
  ('english-eiken-2', 'english-eiken-pre2'),
  ('english-eiken-pre1', 'english-eiken-2'),
  ('english-eiken-1', 'english-eiken-pre1'),
  ('english-toefl-70', 'english-toefl-60'),
  ('english-toefl-80', 'english-toefl-70'),
  ('english-toefl-90', 'english-toefl-80'),
  ('english-toefl-100', 'english-toefl-90'),
  ('english-toefl-110', 'english-toefl-100'),
  ('english-ielts-55', 'english-ielts-50'),
  ('english-ielts-60', 'english-ielts-55'),
  ('english-ielts-65', 'english-ielts-60'),
  ('english-ielts-70', 'english-ielts-65'),
  ('english-ielts-75', 'english-ielts-70'),
  ('english-ielts-80', 'english-ielts-75'),
  ('strength-bench-60', 'strength-bench-40'),
  ('strength-bench-80', 'strength-bench-60'),
  ('strength-bench-100', 'strength-bench-80'),
  ('strength-bench-120', 'strength-bench-100'),
  ('strength-bench-140', 'strength-bench-120'),
  ('strength-squat-80', 'strength-squat-60'),
  ('strength-squat-100', 'strength-squat-80'),
  ('strength-squat-120', 'strength-squat-100'),
  ('strength-squat-140', 'strength-squat-120'),
  ('strength-squat-160', 'strength-squat-140'),
  ('strength-squat-180', 'strength-squat-160'),
  ('strength-deadlift-100', 'strength-deadlift-80'),
  ('strength-deadlift-120', 'strength-deadlift-100'),
  ('strength-deadlift-140', 'strength-deadlift-120'),
  ('strength-deadlift-160', 'strength-deadlift-140'),
  ('strength-deadlift-180', 'strength-deadlift-160'),
  ('strength-deadlift-200', 'strength-deadlift-180'),
  ('strength-pullup-5', 'strength-pullup-1'),
  ('strength-pullup-10', 'strength-pullup-5'),
  ('strength-pullup-15', 'strength-pullup-10'),
  ('strength-pullup-20', 'strength-pullup-15'),
  ('strength-pushup-30', 'strength-pushup-10'),
  ('strength-pushup-50', 'strength-pushup-30'),
  ('strength-pushup-100', 'strength-pushup-50'),
  ('strength-grip-50', 'strength-grip-40'),
  ('strength-grip-60', 'strength-grip-50'),
  ('strength-grip-70', 'strength-grip-60')
on conflict do nothing;

commit;
